package lawisAddonDqr1.config;

import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import lawisAddonDqr1.LawisAddonDQR01;
import net.minecraftforge.common.config.Configuration;

/*
 * コンフィグ設定の中心となるクラス。
 * 「TNT MODDERS」様の「MOD製作チュートリアル」を参考にさせていただきました。
 * https://www63.atwiki.jp/akasatanahama/pages/131.html
 */
public class LadConfigCore {
	public static final String ROOM = "Room";
	private static final String REDUCTION = ROOM + ".Reduction";
	public static Configuration cfg;

	// 負荷軽量
	public static boolean isRoomReduction = false;

	public static void loadConfig(FMLPreInitializationEvent event) {
		// net.minecraftforge.common.config.Configurationのインスタンスを生成する。
		cfg = new Configuration(event.getSuggestedConfigurationFile(), LawisAddonDQR01.MOD_VERSION, true);
		// 初期化する。
		initConfig();
		// コンフィグファイルの内容を変数と同期させる。
		syncConfig();
	}

	// コンフィグの初期化
	private static void initConfig() {
		// ROOM 戦闘部屋関連
		cfg.addCustomCategoryComment(ROOM, "A settings of rooms generated by " + LawisAddonDQR01.MOD_NAME + ".");
		cfg.setCategoryLanguageKey(ROOM, "config.lad.category.room");

		// REDUCTION 負荷軽減用
		cfg.addCustomCategoryComment(REDUCTION, "The settings of size of rooms for workload reduction.");
		cfg.setCategoryLanguageKey(REDUCTION, "config.lad.category.reduction");
		// cfg.setCategoryRequiresMcRestart(REDUCTION, true);
	}

	// コンフィグの同期
	public static void syncConfig() {
		/* 変数への反映 */
		// ROOM 戦闘部屋関連
		isRoomReduction = cfg.getBoolean("Room Reduction", REDUCTION, isRoomReduction, "When this setting is true, large rooms become smaller.", "config.lad.category.reduction");
		/* コンフィグファイルの保存 */
		cfg.save();
	}
}
