package lawisAddonDqr1.config;

import cpw.mods.fml.common.ModMetadata;
import lawisAddonDqr1.LawisAddonDQR01;

/*
 * mc_mod.infoと同様の内容。
 */
public class LadInfoCore {
	public static void registerInfo(ModMetadata meta) {
		meta.modId = LawisAddonDQR01.MOD_ID;
		meta.name = LawisAddonDQR01.MOD_NAME;
		meta.description = "Lawi's Addon for DQR #01";
		meta.version = LawisAddonDQR01.MOD_VERSION;
		meta.url = "http://lawiss.com/minecraft-modding/archives/";
		meta.authorList.add("Lawillia");
		meta.credits = "";
		meta.logoFile = "";
		meta.autogenerated = false;
	}
}
